### PR TITLE
Make the project compile

### PR DESCRIPTION
**Pull request by superjohan**
The project compiles now, but the generated app itself does not work. There are also tons of warnings.

This basically depends on SDL being installed via Homebrew to the default location now. Probably not a good idea in the long run.

### CODE REVIEW

**Comment by superjohan** [comment]
The problem with getting it to run is that the version of libpng used to compile is not the same that's being used at runtime.

```libpng warning: Application built with libpng-1.6.26 but running with 1.5.7
Error: Skin[default]: Cannot load toolbar.png
```

**Comment by esaruoho** [comment]
@superjohan any idea how to yank out the "wrong" libpng and just compile & use the "right" libpng?
How can a version discrepancy like this occur? Is there a way to evade it?

**Comment by esaruoho** [comment]
@superjohan regarding brew SDL, I'm fine with that, I can just 
```
brew install sdl
```
and it'll work :)

homebrew owns!
ideal situation is to get this to compile and work fully and then push it into a brew cask.

**Comment by superjohan** [comment]
I'm honestly no expert, but I think it's using a dynamically linked libpng now, which is whatever the OS is providing (I think), whereas the app was compiled with the one from homebrew. I haven't done enough research to figure out how to get it to use a static version.

**Comment by superjohan** [comment]
By the way, if you're having trouble compiling, my config while preparing this was macOS 10.13 beta 3 with the latest Xcode 9 beta.

**Comment by esaruoho** [comment]
@superjohan maybe one could try and remove the libpng framework and make a symbolic link to the libpng on homebrew then? I'm really not sure how to create symbolic links to homebrew in an xcodeproject, but it seems like it wouldn't be impossible since you did the sdl symbolic link to homebrew, and now there's a need for libpng from homebrew too

regards 10.013 beta 3 xcode 9 beta - ouch, there's probably no way to get back to OSX 10.11 on the current xcodeproj then? I'll have to see what happens when I do a git pull...

**Comment by superjohan** [comment]
I didn't upgrade the project for Xcode 9, so it should be fine on older versions.

**Comment by esaruoho** [comment]
awesome, thanks!

**Pull request merged**
